version: '3'

networks:
    nginx-php73-mysql:

services:

    # nginx
    nginx-service:
        image: nginx:stable-alpine
        container_name: nginx-container
        ports:
            - "8080:80"
        volumes:
            - ./../subscription-management-api:/var/www/project
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php73-service
            - mysql-service
        networks:
            - nginx-php73-mysql

    # php
    php73-service:
        build:
            context: .
            dockerfile: ./php/Dockerfile
        container_name: php73
        depends_on:
            - mysql-service
        volumes:
            - ./../subscription-management-api:/var/www/project
        working_dir: /var/www/project
        networks:
            - nginx-php73-mysql

    # mysql
    mysql-service:
        image: mysql:5.6
        container_name: mysql-container
        privileged: true
        ports:
            - "4306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always # always restart unless stopped manually
        environment:
            MYSQL_DATABASE: 'subscription_management'
            MYSQL_ROOT_USER: root
            MYSQL_ROOT_PASSWORD: root
            MYSQL_PASSWORD: root
        networks:
            - nginx-php73-mysql
